# title: "Project: Aligning LLM Planners with Human Preferences via Reinforced Self-Training for Housekeeping Robots"
description: "This is the project homepage for LLM-Personalize"
navbar-links:
  Home: '/'
