title: "Project LLM-Personalize"
description: "Project Webpage for the LLM-Personalize Project"
include: ['/_includes']
sass:
  sass_dir: _sass
  style: compressed

theme: minima
# Assuming you are using a theme called 'minima'; replace with your theme's name if different.

# Add this line to reference your custom CSS
custom_css: "assets/css/custom.css"
